WizTelemetry/prometheus-charts

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/templates/rbac-configmap.yaml
add the missing namespace in rbac-config configmap
- fixes #
> [prometheus-node-exporter] fix missing namespace

- charts/kube-prometheus-stack/Chart.lock
- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
- charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
- charts/kube-prometheus-stack/values.yaml
update some namespace configs so that they can be overrided by `namespaceOverride`
- fixes #
> [kube-prometheus-stack] update some namespace configs

- charts/kube-state-metrics/Chart.yaml
- charts/kube-state-metrics/README.md
- charts/kube-state-metrics/templates/NOTES.txt
- charts/kube-state-metrics/templates/_helpers.tpl
- charts/kube-state-metrics/templates/ciliumnetworkpolicy.yaml
- charts/kube-state-metrics/templates/crs-configmap.yaml
- charts/kube-state-metrics/templates/deployment.yaml
- charts/kube-state-metrics/templates/extra-manifests.yaml
- charts/kube-state-metrics/templates/networkpolicy.yaml
- charts/kube-state-metrics/templates/rbac-configmap.yaml
- charts/kube-state-metrics/templates/role.yaml
- charts/kube-state-metrics/templates/serviceaccount.yaml
- charts/kube-state-metrics/templates/servicemonitor.yaml
- charts/kube-state-metrics/templates/verticalpodautoscaler.yaml
- charts/kube-state-metrics/values.yaml
Synchronize upstream updates with no additional maintenance
- fixes #
> [kube-state-metrics] sync upstream update

- charts/kube-prometheus-stack/Chart.lock
- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/extension_values.yaml
- charts/kube-prometheus-stack/values.yaml
customizing kubesphere-prometheus-stack default value
- fixes #
> [kube-prometheus-stack] customizing kubesphere-prometheus-stack default value

- charts/kube-prometheus-stack/Chart.lock
- charts/kube-prometheus-stack/Chart.yaml
upgrade dependencies
- fixes #
> [kube-prometheus-stack] upgrade dependencies

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/README.md
- charts/prometheus-blackbox-exporter/templates/NOTES.txt
- charts/prometheus-blackbox-exporter/templates/_helpers.tpl
- charts/prometheus-blackbox-exporter/templates/daemonset.yaml
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/prometheus-blackbox-exporter/templates/extra-manifests.yaml
- charts/prometheus-blackbox-exporter/templates/ingress.yaml
- charts/prometheus-blackbox-exporter/templates/rbac-configmap.yaml
- charts/prometheus-blackbox-exporter/templates/role.yaml
- charts/prometheus-blackbox-exporter/templates/rolebinding.yaml
- charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
- charts/prometheus-blackbox-exporter/templates/service.yaml
- charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
- charts/prometheus-blackbox-exporter/templates/verticalpodautoscaler.yaml
- charts/prometheus-blackbox-exporter/values.yaml
Allow to enable kube-rbac-proxy for prometheus-blackbox-exporter
- fixes #
> [prometheus-blackbox-exporter] Allow to enable kube-rbac-proxy for prometheus-blackbox-exporter

- charts/prometheus-blackbox-exporter/Chart.yaml
- charts/prometheus-blackbox-exporter/templates/cluserrole.yaml
- charts/prometheus-blackbox-exporter/templates/clusterrolebinding.yaml
- charts/prometheus-blackbox-exporter/templates/rbac-configmap.yaml
- charts/prometheus-blackbox-exporter/templates/role.yaml
- charts/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml
- charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml
- charts/prometheus-blackbox-exporter/values.yaml
fix kubeRBACProxy authorization
- fixes #
> [prometheus-blackbox-exporter] fix kubeRBACProxy authorization

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
disable alertManager and thanosRuler
- fixes #
> [kube-prometheus-stack] disable alertManager and thanosRuler

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/unittests/alertmanager/alertmanager_test.yaml
- charts/kube-prometheus-stack/unittests/alertmanager/ingress_test.yaml
- charts/kube-prometheus-stack/values.yaml
update relabelings to keep some metrics, which is mostly used by alerting rules. (This is synced from KSE 3.5)
- fixes #
> [kube-prometheus-stack] update relabelings to keep some metrics

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
The metrics paths of ks-apiserver and ks-controller-manager in 4.x are changed to `/metrics`
- fixes #
> [kube-prometheus-stack] update ks-apiserver and ks-controller-manager metrcis path

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-namespace.rules.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-node.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
> [kube-prometheus-stack] fix recording rules

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/extra-objects.yaml
- charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-cluster.rules.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-node.rules.yaml
- charts/kube-prometheus-stack/values.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
1. update PrometheusRules
2. remoteWrite is added when prometheus agentMode is enabled 
- fixes #
> [kube-prometheus-stack] update PrometheusRules

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] use customized node-exporter chart

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/hack/sync_prometheus_rules.py
- charts/kube-prometheus-stack/templates/prometheus/_rules.tpl
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-etcd.rules.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-namespace.rules.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-node.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
> [kube-prometheus-stack] add etcd rules and fix bugs

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-node.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
> [kube-prometheus-stack] fix recording rule bugs

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-node.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
- fixes #
https://github.com/kubesphere/issues/issues/2656
> fix node:node_pod_utilisation:ratio rule

- charts/alertmanager/.helmignore
- charts/alertmanager/Chart.yaml
- charts/alertmanager/README.md
- charts/alertmanager/ci/config-reload-values.yaml
- charts/alertmanager/templates/NOTES.txt
- charts/alertmanager/templates/_helpers.tpl
- charts/alertmanager/templates/_images.tpl
- charts/alertmanager/templates/_node-selectors.tpl
- charts/alertmanager/templates/configmap.yaml
- charts/alertmanager/templates/ingress.yaml
- charts/alertmanager/templates/ingressperreplica.yaml
- charts/alertmanager/templates/pdb.yaml
- charts/alertmanager/templates/serviceaccount.yaml
- charts/alertmanager/templates/serviceperreplica.yaml
- charts/alertmanager/templates/services.yaml
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/templates/tests/test-connection.yaml
- charts/alertmanager/unittests/__snapshot__/ingress_test.yaml.snap
- charts/alertmanager/unittests/ingress_test.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
support to use global.imageRegistry and global.nodeSelector set by ks-core
- fixes #
> [alertmanager] customize to support to use global.imageRegistry and global.nodeSelector

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-cluster.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
> fix the bug where metrics kube_node_role do not exist

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] upgrade kube-state-metrics version

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-cluster.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
> [kube-prometheus-stack] fix missing unscheduled Pods

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] update custom-resource-state-config

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] fill requirement

- charts/dcgm-exporter/.helmignore
- charts/dcgm-exporter/Chart.yaml
- charts/dcgm-exporter/templates/NOTES.txt
- charts/dcgm-exporter/templates/_helpers.tpl
- charts/dcgm-exporter/templates/daemonset.yaml
- charts/dcgm-exporter/templates/extra-objects.yaml
- charts/dcgm-exporter/templates/metrics-configmap.yaml
- charts/dcgm-exporter/templates/role.yaml
- charts/dcgm-exporter/templates/rolebinding.yaml
- charts/dcgm-exporter/templates/service-monitor.yaml
- charts/dcgm-exporter/templates/service.yaml
- charts/dcgm-exporter/templates/serviceaccount.yaml
- charts/dcgm-exporter/values.yaml
> [dcgm-exporter] add dcgm-exporter

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/templates/_daemonset.tpl
- charts/prometheus-node-exporter/charts/calico-exporter/templates/_images.tpl
- charts/prometheus-node-exporter/charts/calico-exporter/templates/_node-selector.tpl
- charts/prometheus-node-exporter/charts/calico-exporter/templates/deployment.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/values.yaml
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/templates/_daemonset.tpl
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/templates/_images.tpl
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] support to use global.imageRegistry and global.nodeSelector for process-exporter and calico-exporter

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/templates/_images.tpl
- charts/prometheus-node-exporter/charts/calico-exporter/values.yaml
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/prometheus-process-exporter/templates/_images.tpl
- charts/prometheus-node-exporter/templates/_helpers.tpl
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
supple for https://github.com/WhizardTelemetry/prometheus-charts/pull/56
- fixes #
> [prometheus-node-exporter] support to use global.imageRegistry for nginx image

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/_helpers.tpl
- charts/alertmanager/templates/servicemonitor.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
> [alertmanager] add servicemonitor

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/_helpers.tpl
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
> [alertmanager] support to auto set replicas by node num

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/ingressperreplica.yaml
- charts/alertmanager/templates/serviceperreplica.yaml
- charts/alertmanager/templates/services.yaml
- charts/alertmanager/templates/statefulset.yaml
> [alertmanager] fix config in HA

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/statefulset.yaml
the `minReadySeconds` for statefulset is not supported in k8s version below 1.22, so do not set by default.
- fixes #
https://github.com/kubesphere/issues/issues/3806
> [alertmanager] update minReadySeconds set only when it is not 0

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/rules/calico.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] Update calico-exporter to v0.3.0

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/charts/calico-exporter/rules/calico.yaml
> [prometheus-node-exporter] Adjust calico-exporter-rules

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/prometheus/rules-1.14/whizard-telemetry-cluster.rules.yaml
- ks-prometheus/components/whizard-telemetry-mixin/rules/custom.libsonnet
- ks-prometheus/manifests/whizard-telemetry-prometheusRule.yaml
This reverts commit 357ca86c818e70bd3dff094ea93641f9c0bf29af for release-1.0 branch.
- fixes #
> [release-1.0] Revert "[kube-prometheus-stack] update recording rules"

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] update metricDenylist

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
for https://github.com/WhizardTelemetry/prometheus-charts/pull/71#discussion_r1677575422
- fixes #
> [kube-prometheus-stack] remove redundant container_fs.* and keep kube_namespace_status_phase

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/services.yaml
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
sync upstream changes from alertmanager-1.8.0 to alertmanager-1.11.0 tag.
- fixes #
> [alertmanager] sync upstream changes from 1.8.0 to 1.11.0

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] keep node_infiniband_.+ and container_cpu_cfs_periods_total

- charts/prometheus-node-exporter/Chart.yaml
- charts/prometheus-node-exporter/values.yaml
> [prometheus-node-exporter] update serviceAccount.automountServiceAccountToken default to true

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] disable alerting rules that are not disabled

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
It only add the metrics used by `kube-prometheus-stack > Node Exporter / USE Method / Node` dashboard mentioned in https://github.com/kubesphere/project/issues/4595#issuecomment-2297992234
- fixes #
> [kube-prometheus-stack] add node metrics to keep

- charts/alertmanager/Chart.yaml
- charts/alertmanager/templates/_images.tpl
- charts/alertmanager/templates/pre-upgrade.yaml
- charts/alertmanager/templates/statefulset.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
set podManagementPolicy default to Parallel https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/statefulset.go#L752
- fixes #
> [alertmanager] support to configure podManagementPolicy

- charts/alertmanager/Chart.yaml
- charts/alertmanager/values.schema.json
- charts/alertmanager/values.yaml
> [alertmanager] update probes config

- ks-prometheus/components/whizard-telemetry-mixin/rules/gpu.libsonnet
> add gpu recording rules

- charts/wiztelemetry-monitoring-helper/Chart.yaml
- charts/wiztelemetry-monitoring-helper/hack/sync_prometheus_rules.py
- charts/wiztelemetry-monitoring-helper/templates/wiztelemetry-rules/wiztelemetry-kubelet.rules.yaml
- charts/wiztelemetry-monitoring-helper/templates/wiztelemetry-rules/wiztelemetry-workload.rules.yaml
- ks-prometheus/components/wiztelemetry-mixin/rules/custom.libsonnet
- ks-prometheus/components/wiztelemetry-mixin/rules/kubelet.libsonnet
- ks-prometheus/components/wiztelemetry-mixin/rules/rules.libsonnet
- ks-prometheus/jsonnetfile.json
- ks-prometheus/manifests/wiztelemetry-prometheusRule.yaml
> [wiztelemetry-monitoring-helper] add kubelet rules

- charts/wiztelemetry-monitoring-helper/Chart.yaml
- charts/wiztelemetry-monitoring-helper/templates/etcd-endpoint-secret-generator-job.yaml
> [wiztelemetry-monitoring-helper] optimize etcd-endpoint-secret-generator-job

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] update values

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
> [kube-prometheus-stack] set enableRemoteWriteReceiver to true
